# Generated by Django 5.2 on 2025-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
