# Generated by Django 5.2 on 2025-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
