# Generated by Django 5.2 on 2025-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='genre',
            field=models.CharField(choices=[('inspiration', 'Inspiration'), ('love', 'Love'), ('humor', 'Humor'), ('life', 'Life'), ('friendship', 'Friendship')], default='inspiration', max_length=100),
        ),
    ]
